server:
  applicationConnectors:
    - type: http
      bindHost: 0.0.0.0
      port: 19020
  adminConnectors:
    - type: http
      bindHost: 127.0.0.1
      port: 19021
populateBluefloodConfigurationSettings: true
cassandraHosts:
 - 127.0.0.1:19180
 - 127.0.0.1:19180
rollupKeyspace: data
luceneDirectory: "/Users/gdusbabek/Desktop/lucene-test-index"
riemann:
  enabled: false
  host: 127.0.0.1
  port: 5555
  prefix: foo
  localhost: 127.0.0.1
  tags: [zee, fee, bee]
  separator: "."
  ttl: 604800
graphite:
  enabled: false
  host: 127.0.0.1
  port: 2003
logging:
  level: INFO
  appenders:
    - type: console
      threshold: DEBUG
      target: stdout
